version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /home/node/app/node_modules # bookmark - means dont try and map the container folder node_modules back to a host folder
            - .:/home/node/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /home/node/app/node_modules # bookmark - means dont try and map the container folder node_modules back to a host folder
            - .:/home/node/app
        command: ["npm", "run", "test"]
