# build production react code
FROM node:alpine as builder

WORKDIR /app

COPY . .

RUN npm install
RUN npm run build

# build production nginx container and copy production react code
FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html

# nginx image default command is fine, dont need to override